version: 1.0.{build}
environment:
  nodejs_version: "4.2.2"
cache:
- packages
- node_modules
before_build:
- cmd: nuget restore
- cmd: npm install typings
- cmd: cd AureliaExample\AureliaExample && npm install
build:
  verbosity: minimal